In [17]:
import numpy as np

In [18]:
#NP.sort()

a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))

[ 9 43 56 49  9 71 75  9 27 20 95 37 38  2 90]
[ 2  9  9  9 20 27 37 38 43 49 56 71 75 90 95]


In [19]:
b = np.random.randint(1,100,24).reshape(4,6)
print(b)
print(np.sort(b,axis=0))

[[72 40 88 20 81 97]
 [88  7 71 79 14 38]
 [95 76 82 84 81 19]
 [10 75 63 48 38 13]]
[[10  7 63 20 14 13]
 [72 40 71 48 38 19]
 [88 75 82 79 81 38]
 [95 76 88 84 81 97]]


In [20]:
#np.append
np.append(a,200)

array([  9,  43,  56,  49,   9,  71,  75,   9,  27,  20,  95,  37,  38,
         2,  90, 200])

In [21]:
b

array([[72, 40, 88, 20, 81, 97],
       [88,  7, 71, 79, 14, 38],
       [95, 76, 82, 84, 81, 19],
       [10, 75, 63, 48, 38, 13]])

In [22]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[72., 40., 88., 20., 81., 97.,  1.],
       [88.,  7., 71., 79., 14., 38.,  1.],
       [95., 76., 82., 84., 81., 19.,  1.],
       [10., 75., 63., 48., 38., 13.,  1.]])

In [23]:
#np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [24]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
#np.unique
e = np.array([1,2,3,4,5,5,5,6,6,6,6])
print(np.unique(e))

[1 2 3 4 5 6]


In [26]:
#np.expand_dims --> get expanded dimensions of an array 
a

array([ 9, 43, 56, 49,  9, 71, 75,  9, 27, 20, 95, 37, 38,  2, 90])

In [27]:
np.expand_dims(a,axis=1)

array([[ 9],
       [43],
       [56],
       [49],
       [ 9],
       [71],
       [75],
       [ 9],
       [27],
       [20],
       [95],
       [37],
       [38],
       [ 2],
       [90]])

In [28]:
#np.where
a

array([ 9, 43, 56, 49,  9, 71, 75,  9, 27, 20, 95, 37, 38,  2, 90])

In [29]:
np.where(a>50)

(array([ 2,  5,  6, 10, 14], dtype=int64),)

In [30]:
#replace all the values > 50 with 0 
print(np.where(a>50,0,a))

[ 9 43  0 49  9  0  0  9 27 20  0 37 38  2  0]


In [31]:
#np.argmax
a

array([ 9, 43, 56, 49,  9, 71, 75,  9, 27, 20, 95, 37, 38,  2, 90])

In [32]:
np.argmax(a)

10

In [33]:
b

array([[72, 40, 88, 20, 81, 97],
       [88,  7, 71, 79, 14, 38],
       [95, 76, 82, 84, 81, 19],
       [10, 75, 63, 48, 38, 13]])

In [34]:
np.argmax(b,axis=1)

array([5, 0, 0, 1], dtype=int64)

In [35]:
#np.argmin
a

array([ 9, 43, 56, 49,  9, 71, 75,  9, 27, 20, 95, 37, 38,  2, 90])

In [106]:
np.argmin(a)

13

In [37]:
#np.cumsum
print(a)
print(np.cumsum(a))

[ 9 43 56 49  9 71 75  9 27 20 95 37 38  2 90]
[  9  52 108 157 166 237 312 321 348 368 463 500 538 540 630]


In [38]:
print(b)
print(np.cumsum(b,axis=1))

[[72 40 88 20 81 97]
 [88  7 71 79 14 38]
 [95 76 82 84 81 19]
 [10 75 63 48 38 13]]
[[ 72 112 200 220 301 398]
 [ 88  95 166 245 259 297]
 [ 95 171 253 337 418 437]
 [ 10  85 148 196 234 247]]


In [39]:
#np.cumprod
np.cumprod(a)

array([          9,         387,       21672,     1061928,     9557352,
         678571992,  -646708152, -1525406072,  1763709016,   914441952,
         972639520,  1627923872,  1731564992,  -831837312, -1850914048])

In [40]:
#np.percentile --> nth percentile of given data 
print(a)
np.percentile(a,99)


[ 9 43 56 49  9 71 75  9 27 20 95 37 38  2 90]


94.3

In [41]:
#np.histogram 
print(len(a))
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]))

15
(array([4, 0, 2, 2, 2, 1, 0, 2, 0, 2], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [42]:
#np.corrcoeff
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [43]:
#np.isin
a

array([ 9, 43, 56, 49,  9, 71, 75,  9, 27, 20, 95, 37, 38,  2, 90])

In [44]:
np.isin(a,[11,12,63,28,10,50,60,70])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [45]:
#np.flip
np.flip(a)

array([90,  2, 38, 37, 95, 20, 27,  9, 75, 71,  9, 49, 56, 43,  9])

In [46]:
b

array([[72, 40, 88, 20, 81, 97],
       [88,  7, 71, 79, 14, 38],
       [95, 76, 82, 84, 81, 19],
       [10, 75, 63, 48, 38, 13]])

In [47]:
np.flip(b,axis=0)

array([[10, 75, 63, 48, 38, 13],
       [95, 76, 82, 84, 81, 19],
       [88,  7, 71, 79, 14, 38],
       [72, 40, 88, 20, 81, 97]])

In [48]:
#np.put --> changing multiple elements permanently !
a

array([ 9, 43, 56, 49,  9, 71, 75,  9, 27, 20, 95, 37, 38,  2, 90])

In [49]:
np.put(a,[0,1],[110,156])

In [50]:
print(a)

[110 156  56  49   9  71  75   9  27  20  95  37  38   2  90]


In [51]:
#np.delete
print(a)

[110 156  56  49   9  71  75   9  27  20  95  37  38   2  90]


In [52]:
np.delete(a,[0,2,4])

array([156,  49,  71,  75,   9,  27,  20,  95,  37,  38,   2,  90])

In [53]:
print(a)

[110 156  56  49   9  71  75   9  27  20  95  37  38   2  90]


In [54]:
#SET FUNCTIONS
np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.in1d

<function in1d at 0x000002414340B630>

In [55]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
np.intersect1d(m,n)

array([3, 4, 5])

In [57]:
np.setdiff1d(m,n)

array([1, 2])

In [58]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [59]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

In [60]:
#np.clip
np.clip(a,a_min=25,a_max=75)

array([75, 75, 56, 49, 25, 71, 75, 25, 27, 25, 75, 37, 38, 25, 75])