In [1]:
import numpy as np 
np.array([1,2,3])

array([1, 2, 3])

In [2]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
#testing none are zero 
x = np.array([1,2,3])
np.all(x)
y = np.array([0,1,2,3])
np.all(y)

False

In [11]:
#testing if any non-zero  
x = np.array([0,1,2])
#np.any(x)
y = np.array([0,0,0])
np.any(y)

False

In [18]:
#checking for valid values 
x = np.array([1,2,3,np.nan])
y = np.array([4,5,6,np.inf])
#print(y)
np.isfinite(x)
#np.isfinite(y)

array([ True,  True,  True, False])

In [20]:
#checking for pos/neg infinite Numbers 
x = np.array([1,2,3,-np.inf, np.inf,10])
np.isposinf(x)
#np.isneginf(x)

array([False, False, False, False,  True, False])

In [21]:
#checking for nan values 
x = np.array([1,2,3,np.nan,10])
np.isnan(x)

array([False, False, False,  True, False])

In [24]:
x = np.array([1,2,3,4,5])
y =np.array([1,5,2,3,4])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[False False  True  True  True]
[ True False  True  True  True]
[False  True False False False]
[ True  True False False False]


In [35]:
x = np.array([1,2,3,4,5])
y =np.array([1,5,2,3,4])
z = np.array([1,2,4,5,7])
x1 = np.array([10,11,0,-1,2])
print(np.min((x,y,z,x1),axis=0))

[ 1  2  0 -1  2]


In [43]:
x = np.array([1,7,12,105,1,3,5,1,16,16])
print(x.nbytes)
print(x.size)
print(x.itemsize)
print("%d bytes" % (x.size * x.itemsize)) 

40
10
4
40 bytes


In [44]:
#array of 10 zeros 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
#array of 10 ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
#array of 10 fives 
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [49]:
#numpy array from 30 to 70 
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [50]:
#now just even from 30 to 70 
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [74]:
#creating a matrix of 3 x 3 dimensions
#np.arange(1,10).reshape(3,3)
#np.random.randint(1,10,9).reshape(3,3)
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x.size)


9


In [81]:
# generate a random number between 0 and 1 
rand_num = np.random.normal(0, 1, 1)
print(rand_num)

[0.62411949]


In [83]:
# standard random number 15 of them 
np.random.normal(0,1,15)

array([ 0.14654137, -0.51167581, -0.18593468, -0.87355577,  0.52333329,
        1.75404895,  0.86962668,  0.01681596, -0.25187622, -0.42831707,
       -0.52588393, -0.20206922,  0.17059778, -1.79783593, -0.93514114])

In [89]:
#create a vetctor between numbers 15 and 45 and just print every element except the first and the last element ! 
t_array = np.arange(15,46)
t_array = t_array.T
print(t_array)
print(t_array[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44]


In [90]:
#create 3*4 array and iterate through it ! 
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
#evenly distributed vector with length 10 between 5 and 50 
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [92]:
#Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
np.random.randint(0,10,5)

array([9, 3, 0, 3, 6])

In [95]:
x = np.random.randint(1,10,3)
y = np.random.randint(1,10,3)
print(x)
print(y)
print(x * y)

[6 4 3]
[8 9 1]
[48 36  3]


In [97]:
# 3*4 matrix filled with values from 10 to 21 
np.random.randint(10,22,12).reshape(3,4)

array([[17, 18, 18, 16],
       [12, 14, 10, 17],
       [17, 14, 10, 14]])

In [116]:
#write a program to find the number of rows and columns in the matrix 
x = np.arange(1,10)
y = np.arange(1,11).reshape(2,5)
z = np.arange(1,10).reshape(3,3)
rows = x.shape
rows_y,columns_y = y.shape
rows_z,columns_z = z.shape

print(x)
print()
print(y)
print()
print(z)
print()
print("rows columns for x ",rows)
print("rows columns for y ",rows_y,columns_y)
print("rows columns for z ",rows_z,columns_z)

[1 2 3 4 5 6 7 8 9]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

rows columns for x  (9,)
rows columns for y  2 5
rows columns for z  3 3


In [118]:
# 3x3 identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])